<?php
/**
 * OAuth 2.0 Authorization Code flow with PKCE.
 *
 * @package MediagraphAssets
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Handles connecting, refreshing, and disconnecting.
 */
class Mediagraph_OAuth {

	/**
	 * Public client ID registered in Doorkeeper.
	 *
	 * PKCE public client: there is no secret.
	 *
	 * @var string
	 */
	const CLIENT_ID = 'wordpress-plugin-public-client';

	/**
	 * Requested scopes.
	 *
	 * @var string
	 */
	const SCOPE = 'read write';

	/**
	 * How long a pending authorization stays valid.
	 *
	 * @var int
	 */
	const HANDSHAKE_TTL = 900;

	/**
	 * Credential store.
	 *
	 * @var Mediagraph_Credentials
	 */
	private $credentials;

	/**
	 * Guard against recursive refreshes within one request.
	 *
	 * @var bool
	 */
	private $refreshing = false;

	/**
	 * Constructor.
	 *
	 * @param Mediagraph_Credentials $credentials Credential store.
	 */
	public function __construct( Mediagraph_Credentials $credentials ) {
		$this->credentials = $credentials;
	}

	/**
	 * Register hooks.
	 *
	 * @return void
	 */
	public function register_hooks() {
		add_action( 'admin_menu', array( $this, 'register_callback_page' ) );
		add_action( 'admin_post_mediagraph_connect', array( $this, 'handle_connect' ) );
		add_action( 'admin_init', array( $this, 'maybe_handle_callback' ) );
	}

	/**
	 * Register the hidden callback screen.
	 *
	 * The redirect lands on admin.php?page=mediagraph-callback; registering the
	 * page keeps WordPress from rendering a "you do not have permission" error
	 * before our admin_init handler has run.
	 *
	 * @return void
	 */
	public function register_callback_page() {
		add_submenu_page(
			'',
			__( 'Connecting to Mediagraph', 'mediagraph-assets' ),
			__( 'Connecting to Mediagraph', 'mediagraph-assets' ),
			'manage_options',
			'mediagraph-callback',
			array( $this, 'render_callback_page' )
		);
	}

	/**
	 * Placeholder screen.
	 *
	 * maybe_handle_callback() always redirects before this runs; it exists so
	 * the route is never a blank page if that changes.
	 *
	 * @return void
	 */
	public function render_callback_page() {
		echo '<div class="wrap"><h1>' . esc_html__( 'Connecting to Mediagraph…', 'mediagraph-assets' ) . '</h1></div>';
	}

	/**
	 * The redirect URI registered with the authorization server.
	 *
	 * @return string
	 */
	public function redirect_uri() {
		return admin_url( 'admin.php?page=mediagraph-callback' );
	}

	/**
	 * Start the handshake.
	 *
	 * State and the PKCE verifier are generated here, on an explicit user
	 * action, and scoped to the acting user. In 1.x they were regenerated by
	 * merely rendering the settings page, so opening it in a second tab broke
	 * an in-flight connection.
	 *
	 * @return void
	 */
	public function handle_connect() {
		check_admin_referer( 'mediagraph_connect' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'You do not have permission to connect this site to Mediagraph.', 'mediagraph-assets' ) );
		}

		$state    = wp_generate_password( 40, false, false );
		$verifier = $this->generate_code_verifier();

		set_transient( $this->handshake_key(), array(
			'state'    => $state,
			'verifier' => $verifier,
		), self::HANDSHAKE_TTL );

		$params = array(
			'client_id'             => self::CLIENT_ID,
			'redirect_uri'          => $this->redirect_uri(),
			'response_type'         => 'code',
			'scope'                 => self::SCOPE,
			'state'                 => $state,
			'code_challenge'        => $this->base64_url_encode( hash( 'sha256', $verifier, true ) ),
			'code_challenge_method' => 'S256',
		);

		$url = add_query_arg(
			array_map( 'rawurlencode', $params ),
			trailingslashit( $this->credentials->browser_base_url() ) . 'oauth/authorize'
		);

		wp_redirect( $url );
		exit;
	}

	/**
	 * Complete the handshake when the authorization server redirects back.
	 *
	 * @return void
	 */
	public function maybe_handle_callback() {
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- OAuth state is the CSRF token here.
		if ( ! isset( $_GET['page'] ) || 'mediagraph-callback' !== $_GET['page'] ) {
			return;
		}

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'You do not have permission to connect this site to Mediagraph.', 'mediagraph-assets' ) );
		}

		// phpcs:disable WordPress.Security.NonceVerification.Recommended
		if ( isset( $_GET['error'] ) ) {
			$description = isset( $_GET['error_description'] )
				? sanitize_text_field( wp_unslash( $_GET['error_description'] ) )
				: sanitize_text_field( wp_unslash( $_GET['error'] ) );

			$this->fail( $description );
		}

		$code  = isset( $_GET['code'] ) ? sanitize_text_field( wp_unslash( $_GET['code'] ) ) : '';
		$state = isset( $_GET['state'] ) ? sanitize_text_field( wp_unslash( $_GET['state'] ) ) : '';
		// phpcs:enable WordPress.Security.NonceVerification.Recommended

		if ( '' === $code ) {
			$this->fail( __( 'Mediagraph did not return an authorization code.', 'mediagraph-assets' ) );
		}

		$handshake = get_transient( $this->handshake_key() );
		delete_transient( $this->handshake_key() );

		if ( ! is_array( $handshake ) || empty( $handshake['state'] ) || empty( $handshake['verifier'] ) ) {
			$this->fail( __( 'This connection attempt expired. Please click Connect and finish authorizing within 15 minutes.', 'mediagraph-assets' ) );
		}

		if ( ! hash_equals( (string) $handshake['state'], $state ) ) {
			$this->fail( __( 'The security check on the Mediagraph response failed. Please try connecting again.', 'mediagraph-assets' ) );
		}

		$tokens = $this->request_tokens( array(
			'grant_type'    => 'authorization_code',
			'code'          => $code,
			'redirect_uri'  => $this->redirect_uri(),
			'client_id'     => self::CLIENT_ID,
			'code_verifier' => $handshake['verifier'],
		) );

		if ( is_wp_error( $tokens ) ) {
			$this->fail( $tokens->get_error_message() );
		}

		$this->credentials->store_tokens( $tokens );
		Mediagraph_Cache::flush();

		$this->refresh_identity();

		wp_safe_redirect( add_query_arg( 'mg_notice', 'connected', Mediagraph_Settings::url() ) );
		exit;
	}

	/**
	 * Exchange the refresh token for a new access token.
	 *
	 * @return bool True when a fresh access token is now stored.
	 */
	public function refresh() {
		if ( $this->refreshing ) {
			return false;
		}

		$refresh_token = $this->credentials->refresh_token();

		if ( '' === $refresh_token ) {
			return false;
		}

		$this->refreshing = true;

		$tokens = $this->request_tokens( array(
			'grant_type'    => 'refresh_token',
			'refresh_token' => $refresh_token,
			'client_id'     => self::CLIENT_ID,
		) );

		$this->refreshing = false;

		if ( is_wp_error( $tokens ) ) {
			Mediagraph_Logger::error( 'Token refresh failed', array( 'error' => $tokens->get_error_message() ) );

			// An invalid_grant means the refresh token is dead; keeping it
			// would make every later request pay for a doomed refresh.
			if ( 'mediagraph_invalid_grant' === $tokens->get_error_code() ) {
				delete_option( Mediagraph_Credentials::REFRESH_TOKEN );
			}

			return false;
		}

		$this->credentials->store_tokens( $tokens );
		Mediagraph_Logger::debug( 'Access token refreshed' );

		return true;
	}

	/**
	 * Re-read identity from /api/whoami and cache it.
	 *
	 * @return array|WP_Error
	 */
	public function refresh_identity() {
		$whoami = mediagraph()->client->get( 'api/whoami' );

		if ( is_wp_error( $whoami ) ) {
			return $whoami;
		}

		if ( is_array( $whoami ) ) {
			$this->credentials->store_identity( $whoami );
		}

		return $whoami;
	}

	/**
	 * Disconnect the site.
	 *
	 * @return void
	 */
	public function disconnect() {
		$this->credentials->forget();
	}

	/**
	 * POST to the token endpoint.
	 *
	 * @param array $body Form body.
	 * @return array|WP_Error
	 */
	private function request_tokens( array $body ) {
		$response = wp_remote_post(
			trailingslashit( $this->credentials->api_base_url() ) . 'oauth/token',
			array(
				'body'    => $body,
				'timeout' => 30,
			)
		);

		if ( is_wp_error( $response ) ) {
			return $response;
		}

		$status = wp_remote_retrieve_response_code( $response );
		$data   = json_decode( wp_remote_retrieve_body( $response ), true );

		if ( 200 !== (int) $status || ! is_array( $data ) || empty( $data['access_token'] ) ) {
			$error   = is_array( $data ) && ! empty( $data['error'] ) ? (string) $data['error'] : 'token_request_failed';
			$message = is_array( $data ) && ! empty( $data['error_description'] )
				? (string) $data['error_description']
				: __( 'Mediagraph rejected the token request.', 'mediagraph-assets' );

			Mediagraph_Logger::error(
				'Token endpoint returned an error',
				array(
					'status'     => $status,
					'error'      => $error,
					'grant_type' => isset( $body['grant_type'] ) ? $body['grant_type'] : '',
				)
			);

			$code = 'invalid_grant' === $error ? 'mediagraph_invalid_grant' : 'mediagraph_token_error';

			return new WP_Error( $code, $message, array( 'status' => $status ) );
		}

		return $data;
	}

	/**
	 * Per-user transient key for the pending handshake.
	 *
	 * @return string
	 */
	private function handshake_key() {
		return 'mediagraph_oauth_handshake_' . get_current_user_id();
	}

	/**
	 * Generate a PKCE code verifier.
	 *
	 * RFC 7636 requires 43-128 characters from the unreserved set.
	 *
	 * @return string
	 */
	private function generate_code_verifier() {
		if ( function_exists( 'random_bytes' ) ) {
			try {
				return $this->base64_url_encode( random_bytes( 48 ) );
			} catch ( Exception $e ) { // phpcs:ignore Generic.CodeAnalysis.EmptyStatement.DetectedCatch
				// Fall through to the WordPress helper below.
			}
		}

		return $this->base64_url_encode( wp_generate_password( 64, false, false ) );
	}

	/**
	 * Base64url encoding without padding (RFC 4648 §5).
	 *
	 * @param string $data Raw bytes.
	 * @return string
	 */
	private function base64_url_encode( $data ) {
		return rtrim( strtr( base64_encode( $data ), '+/', '-_' ), '=' ); // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.obfuscation_base64_encode
	}

	/**
	 * Abort the handshake with a readable message on the settings screen.
	 *
	 * 1.x called wp_die() here, which dumped the user on a dead-end white page
	 * with no way back.
	 *
	 * @param string $message Failure reason.
	 * @return void
	 */
	private function fail( $message ) {
		delete_transient( $this->handshake_key() );

		wp_safe_redirect(
			add_query_arg(
				array(
					'mg_notice' => 'connect_failed',
					'mg_detail' => rawurlencode( $message ),
				),
				Mediagraph_Settings::url()
			)
		);
		exit;
	}
}
